# Generated by Django 4.2.2 on 2023-06-28 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inv_city', to='product.city', verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='inventoryproduct',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inp_inventory', to='product.inventory', verbose_name='انبار'),
        ),
        migrations.AlterField(
            model_name='inventoryproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inp_product', to='product.product', verbose_name='محصول'),
        ),
    ]
