# Generated by Django 4.2.2 on 2023-06-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='نام')),
                ('price', models.PositiveBigIntegerField(verbose_name='قیمت')),
                ('quantity', models.PositiveIntegerField(verbose_name='موجودی')),
                ('unit', models.CharField(choices=[('kg', 'کیلوگرم'), ('pack', 'بسته'), ('num', 'عدد')], max_length=20, verbose_name='واحد')),
                ('image', models.ImageField(upload_to='product/%Y/%m/%d/', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
