# Generated by Django 4.2.2 on 2023-06-28 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ردیف')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='نام شهر')),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهر ها',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='نام انبار')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_city', to='product.city', verbose_name='شهر')),
            ],
            options={
                'verbose_name': 'انبار',
                'verbose_name_plural': 'انبار ها',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product/%Y/%M/%D/', verbose_name='تصویر'),
        ),
        migrations.CreateModel(
            name='InventoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='موجودی کالا')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_city', to='product.inventory', verbose_name='انبار')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_product', to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'موجودی انبار',
                'verbose_name_plural': 'موجودی انبار ها',
                'unique_together': {('product', 'inventory')},
            },
        ),
    ]
