# Generated by Django 4.2.2 on 2023-06-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_city_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product/%Y/%B/%d/', verbose_name='تصویر'),
        ),
    ]
