# Generated by Django 4.2.2 on 2023-06-28 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0005_alter_inventory_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بازبینی'), ('deliver', 'آماده ارسال'), ('Post', 'ارسال شده'), ('cancel', 'لفو شده')], max_length=15, verbose_name='وضعیت سفارش')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='O_inventory', to='product.inventory', verbose_name='انبار')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='O_product', to='product.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='O_user', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش ها',
            },
        ),
    ]
