# Generated by Django 4.2.2 on 2023-07-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.PositiveBigIntegerField(default=200000, verbose_name='قیمت کالا'),
            preserve_default=False,
        ),
    ]
