# Generated by Django 4.2.2 on 2023-07-01 18:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='create',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now, verbose_name='زمان ثبت سفارش'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار بازبینی'), ('deliver', 'آماده ارسال'), ('Post', 'ارسال شده'), ('cancel', 'لغو شده')], max_length=15, verbose_name='وضعیت سفارش'),
        ),
    ]
